### ISSUE TITLE
Object spread operator not available until nodejs version 8.5(?)

### ISSUE THREAD

**Issue by ReinsBrain** [rebelstackio/ayEs#1]
https://github.com/rebelstackio/ayEs/blob/5c8d713af539236caae470e7c60ac66eb90bdbd0/lib/respond/respond.js#L19

There are only a couple of instances where the object spread operator occurs and I'd like to replace them for backwards-compatibility with earlier versions of node that purport to support es2015 (partially). In this case, the fix might look like:

```javascript
const buildPassthroughObj = function buildPassthroughObj (body, params) {
    switch ( true ) {
        case ( typeof body === 'object' ) : return Object.assign({},body);
        case ( typeof params === 'object' ) : return Object.assign({},params);
        default : return {};
    }
};
```

**Comment by russormes** [comment]
Yep, sorry about that, I was working on this with the latest node installed and got over excited, I think. I'll look out for the PR
